services:
  wiki:
    build:
      dockerfile: site/Dockerfile
      context: .
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    environment:
      BIND: ":80"
      DIFFICULTY: "4"
      METRICS_BIND: ":9090"
      TARGET: "http://wiki"
      OG_PASSTHROUGH: "true"
      OG_EXPIRY_TIME: "24h"
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
